version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:latest

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-averjs-tailwind-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-averjs-tailwind-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/
          paths:
            - repo

  lint: 
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn lint
  
  build: 
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn build
  
  test: 
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn test

workflows:
  version: 2.1
  test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - build:
          requires:
            - install
      - test:
          requires:
            - install